[2025-07-06T16:51:57.810+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_activity_analysis.extract_data manual__2025-07-06T16:51:56.592087+00:00 [queued]>
[2025-07-06T16:51:57.816+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_activity_analysis.extract_data manual__2025-07-06T16:51:56.592087+00:00 [queued]>
[2025-07-06T16:51:57.817+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-06T16:51:57.828+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-06 16:51:56.592087+00:00
[2025-07-06T16:51:57.837+0000] {standard_task_runner.py:57} INFO - Started process 2551 to run task
[2025-07-06T16:51:57.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_activity_analysis', 'extract_data', 'manual__2025-07-06T16:51:56.592087+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/customer_activity_dag.py', '--cfg-path', '/tmp/tmp9x0xnng8']
[2025-07-06T16:51:57.841+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask extract_data
[2025-07-06T16:51:57.853+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T16:51:57.881+0000] {task_command.py:410} INFO - Running <TaskInstance: customer_activity_analysis.extract_data manual__2025-07-06T16:51:56.592087+00:00 [running]> on host bd04a51aafc1
[2025-07-06T16:51:57.945+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='Daniil' AIRFLOW_CTX_DAG_ID='customer_activity_analysis' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T16:51:56.592087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T16:51:56.592087+00:00'
[2025-07-06T16:51:59.176+0000] {logging_mixin.py:150} INFO - Successfully loaded data with shape: (1270564, 22)
[2025-07-06T16:51:59.176+0000] {python.py:183} INFO - Done. Returned value was:               id         sum_a  sum_b  ...  count_i  count_j        date
0        C00313K      0.000000   8.77  ...      0.0      0.0  2023-10-01
1        C11256K      1.280000   0.00  ...      0.0      0.0  2023-10-01
2        C11256K      0.960000   0.00  ...      0.0      0.0  2023-11-01
3        C11256K      0.640000   0.00  ...      0.0      0.0  2024-01-01
4        C11256K      0.570000   0.00  ...      0.0      0.0  2024-02-01
...          ...           ...    ...  ...      ...      ...         ...
1270559  CBZYP6K  11955.375426   0.00  ...      0.0      0.0  2023-11-01
1270560  CBZYP6K  15788.860118   0.00  ...      0.0      0.0  2024-01-01
1270561  CBZYP6K  10987.337202   0.00  ...      0.0      0.0  2024-02-01
1270562  CBZYP6K  12158.722219   0.00  ...      0.0      0.0  2024-03-01
1270563  CBZYP6K  11897.703873   0.00  ...      0.0      0.0  2023-12-01

[1270564 rows x 22 columns]
[2025-07-06T16:52:01.690+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=customer_activity_analysis, task_id=extract_data, execution_date=20250706T165156, start_date=20250706T165157, end_date=20250706T165201
[2025-07-06T16:52:01.739+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-06T16:52:01.766+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
