[2025-07-07T20:12:12.705+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_activity_analysis.transform_data manual__2025-07-07T20:11:58+00:00 [queued]>
[2025-07-07T20:12:12.715+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_activity_analysis.transform_data manual__2025-07-07T20:11:58+00:00 [queued]>
[2025-07-07T20:12:12.715+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T20:12:12.731+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_data> on 2025-07-07 20:11:58+00:00
[2025-07-07T20:12:12.744+0000] {standard_task_runner.py:57} INFO - Started process 2221 to run task
[2025-07-07T20:12:12.746+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_activity_analysis', 'transform_data', 'manual__2025-07-07T20:11:58+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/customer_activity_dag.py', '--cfg-path', '/tmp/tmp32apgare']
[2025-07-07T20:12:12.748+0000] {standard_task_runner.py:85} INFO - Job 96: Subtask transform_data
[2025-07-07T20:12:12.760+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T20:12:12.790+0000] {task_command.py:410} INFO - Running <TaskInstance: customer_activity_analysis.transform_data manual__2025-07-07T20:11:58+00:00 [running]> on host 7a17032e36f4
[2025-07-07T20:12:13.007+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ds_const@mail.ru' AIRFLOW_CTX_DAG_OWNER='Daniil' AIRFLOW_CTX_DAG_ID='customer_activity_analysis' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T20:11:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T20:11:58+00:00'
[2025-07-07T20:12:13.017+0000] {logging_mixin.py:150} INFO - /opt/***/shared_tmp/extract_manual__2025-07-07T20:11:58+00:00.csv
[2025-07-07T20:12:14.236+0000] {logging_mixin.py:150} INFO - Файл /opt/***/shared_tmp/extract_manual__2025-07-07T20:11:58+00:00.csv успешно удалён
[2025-07-07T20:12:14.237+0000] {logging_mixin.py:150} INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!2024-05-01
[2025-07-07T20:12:14.237+0000] {logging_mixin.py:150} INFO - Received date type: <class 'str'>, value: 2024-05-01
[2025-07-07T20:12:14.552+0000] {logging_mixin.py:150} WARNING - Generating flags:   0%|          | 0/10 [00:00<?, ?it/s]
[2025-07-07T20:12:14.563+0000] {logging_mixin.py:150} WARNING - Generating flags: 100%|##########| 10/10 [00:00<00:00, 990.46it/s]
[2025-07-07T20:12:14.859+0000] {python.py:183} INFO - Done. Returned value was: /opt/***/shared_tmp/transform_manual__2025-07-07T20:11:58+00:00.csv
[2025-07-07T20:12:14.881+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=customer_activity_analysis, task_id=transform_data, execution_date=20250707T201158, start_date=20250707T201212, end_date=20250707T201214
[2025-07-07T20:12:14.922+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T20:12:14.943+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
